### import

In [30]:
import numpy as np
import pandas as pd
import matplotlib as mp
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

### README

In [31]:
with open('./raw/m1/README', 'r') as fp:
  readme = fp.read()

FileNotFoundError: [Errno 2] No such file or directory: './raw/m1/README'

In [ ]:
print(readme)

SUMMARY
================================================================================

These files contain 1,000,209 anonymous ratings of approximately 3,900 movies
made by 6,040 MovieLens users who joined MovieLens in 2000.

USAGE LICENSE
================================================================================

Neither the University of Minnesota nor any of the researchers
involved can guarantee the correctness of the data, its suitability
for any particular purpose, or the validity of results based on the
use of the data set.  The data set may be used for any research
purposes under the following conditions:

     * The user may not state or imply any endorsement from the
       University of Minnesota or the GroupLens Research Group.

     * The user must acknowledge the use of the data set in
       publications resulting from the use of the data set, and must
       send us an electronic or paper copy of those publications.

     * The user may not redistribute the data without separate
       permission.

     * The user may not use this information for any commercial or
       revenue-bearing purposes without first obtaining permission
       from a faculty member of the GroupLens Research Project at the
       University of Minnesota.

If you have any further questions or comments, please contact GroupLens
<grouplens-info@cs.umn.edu>.

ACKNOWLEDGEMENTS
================================================================================

Thanks to Shyong Lam and Jon Herlocker for cleaning up and generating the data
set.

FURTHER INFORMATION ABOUT THE GROUPLENS RESEARCH PROJECT
================================================================================

The GroupLens Research Project is a research group in the Department of
Computer Science and Engineering at the University of Minnesota. Members of
the GroupLens Research Project are involved in many research projects related
to the fields of information filtering, collaborative filtering, and
recommender systems. The project is lead by professors John Riedl and Joseph
Konstan. The project began to explore automated collaborative filtering in
1992, but is most well known for its world wide trial of an automated
collaborative filtering system for Usenet news in 1996. Since then the project
has expanded its scope to research overall information filtering solutions,
integrating in content-based methods as well as improving current collaborative
filtering technology.

Further information on the GroupLens Research project, including research
publications, can be found at the following web site:

        http://www.grouplens.org/

GroupLens Research currently operates a movie recommender based on
collaborative filtering:

        http://www.movielens.org/

RATINGS FILE DESCRIPTION
================================================================================

All ratings are contained in the file "ratings.dat" and are in the
following format:

UserID::MovieID::Rating::Timestamp

- UserIDs range between 1 and 6040
- MovieIDs range between 1 and 3952
- Ratings are made on a 5-star scale (whole-star ratings only)
- Timestamp is represented in seconds since the epoch as returned by time(2)
- Each user has at least 20 ratings

USERS FILE DESCRIPTION
================================================================================

User information is in the file "users.dat" and is in the following
format:

UserID::Gender::Age::Occupation::Zip-code

All demographic information is provided voluntarily by the users and is
not checked for accuracy.  Only users who have provided some demographic
information are included in this data set.

- Gender is denoted by a "M" for male and "F" for female
- Age is chosen from the following ranges:

	*  1:  "Under 18"
	* 18:  "18-24"
	* 25:  "25-34"
	* 35:  "35-44"
	* 45:  "45-49"
	* 50:  "50-55"
	* 56:  "56+"

- Occupation is chosen from the following choices:

	*  0:  "other" or not specified
	*  1:  "academic/educator"
	*  2:  "artist"
	*  3:  "clerical/admin"
	*  4:  "college/grad student"
	*  5:  "customer service"
	*  6:  "doctor/health care"
	*  7:  "executive/managerial"
	*  8:  "farmer"
	*  9:  "homemaker"
	* 10:  "K-12 student"
	* 11:  "lawyer"
	* 12:  "programmer"
	* 13:  "retired"
	* 14:  "sales/marketing"
	* 15:  "scientist"
	* 16:  "self-employed"
	* 17:  "technician/engineer"
	* 18:  "tradesman/craftsman"
	* 19:  "unemployed"
	* 20:  "writer"

MOVIES FILE DESCRIPTION
================================================================================

Movie information is in the file "movies.dat" and is in the following
format:

MovieID::Title::Genres

- Titles are identical to titles provided by the IMDB (including
year of release)
- Genres are pipe-separated and are selected from the following genres:

	* Action
	* Adventure
	* Animation
	* Children's
	* Comedy
	* Crime
	* Documentary
	* Drama
	* Fantasy
	* Film-Noir
	* Horror
	* Musical
	* Mystery
	* Romance
	* Sci-Fi
	* Thriller
	* War
	* Western

- Some MovieIDs do not correspond to a movie due to accidental duplicate
entries and/or test entries
- Movies are mostly entered by hand, so errors and inconsistencies may exist

### 데이터 가져오기

오류발생 =>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 3114: invalid continuation byte  

해결방법)
- 1)  0xe9는 UTF-8에서 유효한 단일 바이트 문자가 아니다.
- 2) 0xe9 바이트는 ISO-8859-1(European Latin-1)혹은 cp1252(윈도우 인코딩)로 설정해 준다.

In [ ]:
movies = pd.read_csv('./raw/m1/movies.dat', delimiter='::', header=None, engine='python', encoding='ISO-8859-1' )

In [ ]:
print(movies.shape)

(3883, 3)

In [ ]:
#MovieID::Title::Genres
movies.head()

   0                                   1                             2
0  1                    Toy Story (1995)   Animation|Children's|Comedy
1  2                      Jumanji (1995)  Adventure|Children's|Fantasy
2  3             Grumpier Old Men (1995)                Comedy|Romance
3  4            Waiting to Exhale (1995)                  Comedy|Drama
4  5  Father of the Bride Part II (1995)                        Comedy

In [ ]:
movies.sample(5)

,0,1,2
1419,1444,Guantanamera (1994),Comedy
3530,3599,Anchors Aweigh (1945),Comedy|Musical
2912,2981,"Brother, Can You Spare a Dime? (1975)",Documentary
655,661,James and the Giant Peach (1996),Animation|Children's|Musical
3334,3403,Raise the Titanic (1980),Drama|Thriller

In [ ]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 3883 entries, 0 to 3882
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3883 non-null   int64
 1   1       3883 non-null   str
 2   2       3883 non-null   str
dtypes: int64(1), str(2)
memory usage: 91.1 KB

In [ ]:
movies.set_index(0)  # default : inplace=False

                                       1                             2
0
1                       Toy Story (1995)   Animation|Children's|Comedy
2                         Jumanji (1995)  Adventure|Children's|Fantasy
3                Grumpier Old Men (1995)                Comedy|Romance
4               Waiting to Exhale (1995)                  Comedy|Drama
5     Father of the Bride Part II (1995)                        Comedy
...                                  ...                           ...
3948             Meet the Parents (2000)                        Comedy
3949          Requiem for a Dream (2000)                         Drama
3950                    Tigerland (2000)                         Drama
3951             Two Family House (2000)                         Drama
3952               Contender, The (2000)                Drama|Thriller

[3883 rows x 2 columns]

In [ ]:
movies.head()

   0                                   1                             2
0  1                    Toy Story (1995)   Animation|Children's|Comedy
1  2                      Jumanji (1995)  Adventure|Children's|Fantasy
2  3             Grumpier Old Men (1995)                Comedy|Romance
3  4            Waiting to Exhale (1995)                  Comedy|Drama
4  5  Father of the Bride Part II (1995)                        Comedy

In [ ]:
users = pd.read_csv('./raw/m1/users.dat', sep='::', engine='python', header=None)

In [ ]:
#UserID::Gender::Age::Occupation::Zip-code
users.head()

   0  1   2   3      4
0  1  F   1  10  48067
1  2  M  56  16  70072
2  3  M  25  15  55117
3  4  M  45   7  02460
4  5  M  25  20  55455

In [ ]:
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 6040 entries, 0 to 6039
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       6040 non-null   int64
 1   1       6040 non-null   str
 2   2       6040 non-null   int64
 3   3       6040 non-null   int64
 4   4       6040 non-null   str
dtypes: int64(3), str(2)
memory usage: 236.1 KB

In [ ]:
users.shape

(6040, 5)

In [ ]:
ratings = pd.read_csv('./raw/m1/ratings.dat', sep='::', engine='python', header=None)

In [ ]:
#UserID::MovieID::Rating::Timestamp
ratings.head()

   0     1  2          3
0  1  1193  5  978300760
1  1   661  3  978302109
2  1   914  3  978301968
3  1  3408  4  978300275
4  1  2355  5  978824291

In [ ]:
ratings.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000209 entries, 0 to 1000208
Data columns (total 4 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   0       1000209 non-null  int64
 1   1       1000209 non-null  int64
 2   2       1000209 non-null  int64
 3   3       1000209 non-null  int64
dtypes: int64(4)
memory usage: 30.5 MB

In [ ]:
ratings.shape

(1000209, 4)

### 데이터 전처리(preprocessing)

In [ ]:
print(type(movies))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
print(dir(movies))

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append_internal', '_arith_method', '_arith_method_with_reindex', '_attrs', '_box_col_values', '_can_fast_transpose', '_check_copy_deprecation', '_check_inplace_and_allows_duplicate_labels', '_check_label_or_level_ambiguity', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_combine_frame', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_from_mgr', '_constructor_sliced', '_constructor_sliced_from_mgr', '_dir_additions', '_dir_deletions', '_dispatch_frame_op', '_drop_axis', '_drop_labels_or_levels', '_ensure_valid_index', '_find_valid_index', '_flags', '_flex_arith_method', '_flex_cmp_method', '_from_arrays', '_from_mgr', '_get_agg_axis', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_column_array', '_get_index_resolvers', '_get_item', '_get_label_or_level_values', '_get_numeric_data', '_get_value', '_get_values_for_csv', '_getitem_bool_array', '_getitem_multilevel', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_info_repr', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_homogeneous_type', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_iset_item', '_iset_item_mgr', '_iset_not_inplace', '_iter_column_arrays', '_ixs', '_logical_func', '_logical_method', '_maybe_align_series_as_frame', '_metadata', '_mgr', '_min_count_stat_function', '_module_source', '_needs_reindex_multi', '_pad_or_backfill', '_reduce', '_reduce_axis1', '_reindex_axes', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_columnwise', '_repr_data_resource_', '_repr_fits_horizontal_', '_repr_fits_vertical_', '_repr_html_', '_repr_latex_', '_reset_cache', '_sanitize_column', '_select_dtypes_indices', '_series', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_item', '_set_item_frame_value', '_set_item_mgr', '_set_value', '_setitem_array', '_setitem_frame', '_setitem_slice', '_shift_with_freq', '_should_reindex_frame_op', '_slice', '_stat_function', '_stat_function_ddof', '_to_dict_of_blocks', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'asfreq', 'asof', 'assign', 'astype', 'at', 'at_time', 'attrs', 'axes', 'between_time', 'bfill', 'boxplot', 'clip', 'columns', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'corrwith', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'eval', 'ewm', 'expanding', 'explode', 'ffill', 'fillna', 'filter', 'first_valid_index', 'flags', 'floordiv', 'from_arrow', 'from_dict', 'from_records', 'ge', 'get', 'groupby', 'gt', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'insert', 'interpolate', 'isetitem', 'isin', 'isna', 'isnull', 'items', 'iterrows', 'itertuples', 'join', 'keys', 'kurt', 'kurtosis', 'last_valid_index', 'le', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'melt', 'memory_usage', 'merge', 'min', 'mod', 'mode', 'mul', 'multiply', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pct_change', 'pipe', 'pivot', 'pivot_table', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'query', 'radd', 'rank', 'rdiv', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'select_dtypes', 'sem', 'set_axis', 'set_flags', 'set_index', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'stack', 'std', 'style', 'sub', 'subtract', 'sum', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_feather', 'to_hdf', 'to_html', 'to_iceberg', 'to_json', 'to_latex', 'to_markdown', 'to_numpy', 'to_orc', 'to_parquet', 'to_period', 'to_pickle', 'to_records', 'to_sql', 'to_stata', 'to_string', 'to_timestamp', 'to_xarray', 'to_xml', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']

In [ ]:
#MovieID::Title::Genres
movies.columns

Index([0, 1, 2], dtype='int64')

In [ ]:
# 버전에 따라서는 컬럼명이 숫자일 때 문자열로 써야하는 경우도 있다.
movies.rename(columns={0:'MovieID', 1:'Title', 2:'Genres'}, inplace=True)

In [ ]:
movies.head()

   MovieID                               Title                        Genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy

In [ ]:
#UserID::Gender::Age::Occupation::Zip-code

# 데이터를 읽어올 때 컬럼명을 지정할 수 있다.
users = pd.read_csv('./raw/m1/users.dat', sep='::', engine='python',header=None,
                   names=['UserID','Gender','Age','Occupation','Zip-code'])

In [ ]:
users.head()

   UserID Gender  Age  Occupation Zip-code
0       1      F    1          10    48067
1       2      M   56          16    70072
2       3      M   25          15    55117
3       4      M   45           7    02460
4       5      M   25          20    55455

In [ ]:
#UserID::MovieID::Rating::Timestamp

#ratings.rename(columns={0:'UserID', 1:'MovieID', 2:'Rating', 3:'Timestamp'}, inplace=True)
#ratings.rename(mapper={0:'UserID', 1:'MovieID', 2:'Rating', 3:'Timestamp'}, axis=1, inplace=True )

ratings = pd.read_csv('./raw/m1/ratings.dat', sep='::', engine='python', header=None,
                      names=['UserID','MovieID','Rating','Timestamp'])

In [ ]:
ratings.head()

   UserID  MovieID  Rating  Timestamp
0       1     1193       5  978300760
1       1      661       3  978302109
2       1      914       3  978301968
3       1     3408       4  978300275
4       1     2355       5  978824291

### 데이터 구조 변경

merge와 join 비교

In [ ]:
df = pd.DataFrame({'key':['K0','K1','K2','K3','K4','K5'],
                   'A' : ['A0','A1','A2','A3','A4','A5']})
df

  key   A
0  K0  A0
1  K1  A1
2  K2  A2
3  K3  A3
4  K4  A4
5  K5  A5

In [ ]:
other = pd.DataFrame({'key':['K0','K1','K2'],
                       'B' : ['B0','B1','B2']})
other

  key   B
0  K0  B0
1  K1  B1
2  K2  B2

In [ ]:
# 공통적인 key값이 있는 것만 병합이 된다.
# how의 속성값이 inner이다.
df.merge(other)

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2

In [ ]:
df.head(2)

  key   A
0  K0  A0
1  K1  A1

In [ ]:
other.head(2)

  key   B
0  K0  B0
1  K1  B1

In [ ]:
# join()은 속성의 값이 left(how:str='left')이므로 left outer join을 실행한다.
# left outer join
df.join(other.set_index('key'), on='key')

  key   A    B
0  K0  A0   B0
1  K1  A1   B1
2  K2  A2   B2
3  K3  A3  NaN
4  K4  A4  NaN
5  K5  A5  NaN

In [ ]:
# Left Outer join
other.join(df.set_index('key'), on='key')

  key   B   A
0  K0  B0  A0
1  K1  B1  A1
2  K2  B2  A2

In [ ]:
# Right Outer Join
other.join(df.set_index('key'), on='key', how='right')

    key    B   A
0.0  K0   B0  A0
1.0  K1   B1  A1
2.0  K2   B2  A2
NaN  K3  NaN  A3
NaN  K4  NaN  A4
NaN  K5  NaN  A5

In [ ]:
# Inner Join
other.join(df.set_index('key'), on='key', how='inner')

  key   B   A
0  K0  B0  A0
1  K1  B1  A1
2  K2  B2  A2

merge는 이름이 같은 column을 기준으로 데이터를 합친다.

In [ ]:
# 관람한 영화들에 대해서만 merge를 합다.
data = ratings.merge(users).merge(movies)
data.head()

,UserID,MovieID,Rating,Timestamp,Gender,Age,Occupation,Zip-code,Title,Genres
0,1,1193,5,978300760,F,1,10,48067,One Flew Over the Cuckoo's Nest (1975),Drama
1,1,661,3,978302109,F,1,10,48067,James and the Giant Peach (1996),Animation|Children's|Musical
2,1,914,3,978301968,F,1,10,48067,My Fair Lady (1964),Musical|Romance
3,1,3408,4,978300275,F,1,10,48067,Erin Brockovich (2000),Drama
4,1,2355,5,978824291,F,1,10,48067,"Bug's Life, A (1998)",Animation|Children's|Comedy

In [ ]:
data.columns

Index(['UserID', 'MovieID', 'Rating', 'Timestamp', 'Gender', 'Age',
       'Occupation', 'Zip-code', 'Title', 'Genres'],
      dtype='object')

In [ ]:
#recommendation_data = data.loc[:, 'UserID':'Rating']
#recommendation_data = data.iloc[:, 0:3]
recommendation_data = data[['UserID', 'MovieID', 'Rating']]

In [ ]:
recommendation_data.head(3)

   UserID  MovieID  Rating
0       1     1193       5
1       1      661       3
2       1      914       3

In [ ]:
recommendation_data.shape

(1000209, 3)

pivot

In [ ]:
recommendation_pivot = recommendation_data.pivot(index ='UserID', columns='MovieID', values='Rating')
recommendation_pivot.head()

MovieID,1,2,3,4,5,6,7,8,9,10,...,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952
UserID,,,,,,,,,,,,,,,,,,,,,
1,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
recommendation_pivot.sample(5)

MovieID,1,2,3,4,5,6,7,8,9,10,...,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952
UserID,,,,,,,,,,,,,,,,,,,,,
4146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2127,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN
1211,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
1149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN

missing data처리  
- drop이라는 이름이 붙으면 버리는 기능이다.
- fill이라는 이름이 붙으면 채우는 기능이다.

In [ ]:
recommendation_pivot.fillna(0, inplace=True)

MovieID,1,2,3,4,5,6,7,8,9,10,...,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952
UserID,,,,,,,,,,,,,,,,,,,,,
1,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6036,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6037,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6038,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6039,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6040,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
recommendation_pivot.sample(5)

MovieID,1,2,3,4,5,6,7,8,9,10,...,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952
UserID,,,,,,,,,,,,,,,,,,,,,
4834,3.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,3.0,...,0.0,0.0,0.0,0.0,3.0,3.0,3.0,0.0,0.0,4.0
1848,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3647,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4398,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2821,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

stack, unstack
 - MultiIndex을 만든 다음, unstack으로 pivot과 똑같은 결과를 만들 수 있다.

In [ ]:
recommendation_data.head()

   UserID  MovieID  Rating
0       1     1193       5
1       1      661       3
2       1      914       3
3       1     3408       4
4       1     2355       5

In [ ]:
#set_index에 이름을 여러개 넣으면 MultiIndex가 된다.
data_stack = recommendation_data.set_index(['UserID', 'MovieID']).stack().copy()
data_stack

UserID  MovieID
1       1193     Rating    5
        661      Rating    3
        914      Rating    3
        3408     Rating    4
        2355     Rating    5
                          ..
6040    1091     Rating    1
        1094     Rating    5
        562      Rating    5
        1096     Rating    4
        1097     Rating    4
Length: 1000209, dtype: int64

In [ ]:
data_unstack = recommendation_data.set_index(['UserID', 'MovieID']).unstack().copy()

In [ ]:
data_unstack.head()

        Rating                                               ...            \
MovieID   1    2    3    4    5    6    7    8    9    10    ... 3943 3944
UserID                                                       ...
1          5.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
2          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
3          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
4          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
5          NaN  NaN  NaN  NaN  NaN  2.0  NaN  NaN  NaN  NaN  ...  NaN  NaN


MovieID 3945 3946 3947 3948 3949 3950 3951 3952
UserID
1        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[5 rows x 3706 columns]

In [ ]:
data_unstack.fillna(0, inplace=True)

        Rating                                               ...            \
MovieID   1    2    3    4    5    6    7    8    9    10    ... 3943 3944
UserID                                                       ...
1          5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
2          0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
3          0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
4          0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
5          0.0  0.0  0.0  0.0  0.0  2.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
...        ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
6036       0.0  0.0  0.0  2.0  0.0  3.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
6037       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
6038       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
6039       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
6040       3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0


MovieID 3945 3946 3947 3948 3949 3950 3951 3952
UserID
1        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
...      ...  ...  ...  ...  ...  ...  ...  ...
6036     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
6037     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
6038     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
6039     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
6040     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[6040 rows x 3706 columns]

In [ ]:
data_unstack.head()

        Rating                                               ...            \
MovieID   1    2    3    4    5    6    7    8    9    10    ... 3943 3944
UserID                                                       ...
1          5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
2          0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
3          0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
4          0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
5          0.0  0.0  0.0  0.0  0.0  2.0  0.0  0.0  0.0  0.0  ...  0.0  0.0


MovieID 3945 3946 3947 3948 3949 3950 3951 3952
UserID
1        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 3706 columns]

### 데이터 분석

In [ ]:
recommendation_pivot.head(3)

MovieID,1,2,3,4,5,6,7,8,9,10,...,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952
UserID,,,,,,,,,,,,,,,,,,,,,
1,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
print(recommendation_pivot.loc[2746])
print(recommendation_pivot.loc[2746].value_counts())

MovieID
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
       ...
3948    0.0
3949    0.0
3950    0.0
3951    0.0
3952    0.0
Name: 2746, Length: 3706, dtype: float64
2746
0.0    3649
4.0      28
3.0      18
5.0      11
Name: count, dtype: int64

In [ ]:
# UserID가 2746인 사람이 본 영화 목록
mov_user_2746 = recommendation_pivot.loc[2746]
#print(mov_user_2746)

# mov_user_2746 Series에서 평점이 0보다 큰 값만 가져온다.
mov_user_2746[mov_user_2746>0].head()

MovieID
7      5.0
11     5.0
21     3.0
25     3.0
236    4.0
Name: 2746, dtype: float64

In [ ]:
# UserId 2746인 사람이 매긴 평점별 영화 개수
mov_user_2746[mov_user_2746>0].value_counts()

2746
4.0    28
3.0    18
5.0    11
Name: count, dtype: int64

In [ ]:
mov_user_2746[mov_user_2746>0].unique()

array([5., 3., 4.])

In [ ]:
# 함수를 정의해서 일반화 시킨다.
def movie_seen(user_id):
  return recommendation_pivot.loc[user_id][recommendation_pivot.loc[user_id]>0]

In [ ]:
# 7번 유저가 본 영화
movie_seen(7)

MovieID
6       4.0
110     5.0
349     5.0
377     3.0
380     5.0
442     4.0
457     5.0
474     5.0
480     4.0
589     5.0
648     4.0
733     5.0
861     4.0
1196    5.0
1221    4.0
1270    4.0
1573    4.0
1580    4.0
1610    5.0
1722    4.0
1997    5.0
2028    5.0
2353    5.0
2571    5.0
2916    5.0
3107    3.0
3256    5.0
3418    3.0
3578    3.0
3753    4.0
3793    3.0
Name: 7, dtype: float64

corr
 - corr은 column기준으로 상관관계를 분석해 준다.

In [ ]:
# corr : correlationship(상관관계)
users[['UserID', 'Age']].corr()

          UserID       Age
UserID  1.000000  0.005713
Age     0.005713  1.000000

In [ ]:
recommendation_pivot.head()

MovieID,1,2,3,4,5,6,7,8,9,10,...,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952
UserID,,,,,,,,,,,,,,,,,,,,,
1,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# UserID을 기준으로 상관관계를 구할 것이므로
# column이 UserID여야 한다.
small_test = recommendation_pivot.T.iloc[:500,:500]
small_test

UserID,1,2,3,4,5,6,7,8,9,10,...,491,492,493,494,495,496,497,498,499,500
MovieID,,,,,,,,,,,,,,,,,,,,,
1,5.0,0.0,0.0,0.0,0.0,4.0,0.0,4.0,5.0,5.0,...,2.0,0.0,0.0,0.0,3.0,5.0,0.0,0.0,3.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
510,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
511,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
512,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
513,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
small_test_corr = small_test.corr()
small_test_corr

NameError: name 'small_test' is not defined

UserID가 5인 사람과 상관관계 높은 상위 10명을 뽑을 수 있다.

In [ ]:
# sort_values( )  값의 크기순으로 데이터 순서를 정렬한다.
# ascending=True은 오름차순이다. default로 설정되여 있다.
# ascending=False은 내림차순이다.

# 0 인덱스의 값은 자기 자신을 의미하므로 제외하고 1에서 부터 11미만의 값을 가져온다.
small_test_corr[5].sort_values(ascending=False)[1:11]

UserID
193    0.462310
131    0.446335
281    0.404170
59     0.369056
225    0.360986
208    0.358564
30     0.350050
58     0.339585
23     0.339135
166    0.327965
Name: 5, dtype: float64

In [ ]:
# 함수 정의를 통한 일반화
def nearest_user(user_id, n):
  return small_test_corr.loc[user_id].sort_values(ascending =False)[1: n+1]

In [ ]:
# 5번 유저와 상관관계 높은 3명을 뽑아 올 수 있다.
nearest_user(5, 3)

UserID
193    0.462310
131    0.446335
281    0.404170
Name: 5, dtype: float64

상관관계가 높은 193번과 5번 유저가 본 영화를 비교한다.

In [ ]:
# 193번 유저가 본 영화를 가져온다.
movie_seen(193)

MovieID
1       4.0
11      3.0
21      5.0
28      4.0
34      4.0
       ...
3909    3.0
3911    4.0
3914    4.0
3927    3.0
3929    3.0
Name: 193, Length: 242, dtype: float64

In [ ]:
# 5번 유저가 본 영화를 가져온다.
movie_seen(5)

MovieID
6       2.0
16      3.0
24      1.0
29      5.0
32      4.0
       ...
3728    2.0
3744    1.0
3786    3.0
3793    2.0
3799    3.0
Name: 5, Length: 198, dtype: float64

In [ ]:
# 193번은 보고, 5번은 보지 않은 영화 목록(MovieID)을 뽑아온다.
unseen = set(movie_seen(193).index)- set(movie_seen(5).index)
len(unseen)

193

In [ ]:
unseen_movie = recommendation_data[recommendation_data.MovieID.isin(unseen)]
unseen_movie

         UserID  MovieID  Rating
5             1     1197       3
6             1     1287       5
7             1     2804       5
12            1     2398       4
15            1     2791       4
...         ...      ...     ...
1000195    6040     1079       2
1000197    6040     2020       3
1000201    6040     1080       4
1000205    6040     1094       5
1000208    6040     1097       4

[125759 rows x 3 columns]

In [ ]:
# 193번 유저가 5점 준 영화
unseen_movie[(unseen_movie.Rating==5) & (unseen_movie.UserID==193)]

       UserID  MovieID  Rating
27433     193      649       5
27443     193     1188       5
27453     193     2208       5
27457     193     1265       5
27459     193     1197       5
27467     193     2150       5
27472     193     1358       5
27488     193      912       5
27497     193      922       5
27501     193      926       5
27502     193      928       5
27532     193     1639       5
27535     193      899       5
27537     193     1648       5
27538     193     2520       5
27554     193     1748       5
27580     193     3469       5
27596     193       21       5
27608     193     1104       5
27631     193     3671       5
27636     193     1136       5
27642     193     1148       5
27644     193       82       5
27660     193     1233       5
27663     193     1235       5

In [ ]:
# 추천할 영화제목을 가져온다.
unseen_movie[(unseen_movie.Rating==5) & (unseen_movie.UserID==193)].merge(movies)

,UserID,MovieID,Rating,Title,Genres
0,193,649,5,Cold Fever (Á köldum klaka) (1994),Comedy|Drama
1,193,1188,5,Strictly Ballroom (1992),Comedy|Romance
2,193,2208,5,"Lady Vanishes, The (1938)",Comedy|Mystery|Romance|Thriller
3,193,1265,5,Groundhog Day (1993),Comedy|Romance
4,193,1197,5,"Princess Bride, The (1987)",Action|Adventure|Comedy|Romance
5,193,2150,5,"Gods Must Be Crazy, The (1980)",Comedy
6,193,1358,5,Sling Blade (1996),Drama|Thriller
7,193,912,5,Casablanca (1942),Drama|Romance|War
8,193,922,5,Sunset Blvd. (a.k.a. Sunset Boulevard) (1950),Film-Noir
9,193,926,5,All About Eve (1950),Drama
10,193,928,5,Rebecca (1940),Romance|Thriller
11,193,1639,5,Chasing Amy (1997),Drama|Romance
12,193,899,5,Singin' in the Rain (1952),Musical|Romance
13,193,1648,5,"House of Yes, The (1997)",Comedy|Drama|Thriller
14,193,2520,5,Airport (1970),Drama
15,193,1748,5,Dark City (1998),Film-Noir|Sci-Fi|Thriller
16,193,3469,5,Inherit the Wind (1960),Drama
17,193,21,5,Get Shorty (1995),Action|Comedy|Drama
18,193,1104,5,"Streetcar Named Desire, A (1951)",Drama
19,193,3671,5,Blazing Saddles (1974),Comedy|Western
20,193,1136,5,Monty Python and the Holy Grail (1974),Comedy
21,193,1148,5,"Wrong Trousers, The (1993)",Animation|Comedy
22,193,82,5,Antonia's Line (Antonia) (1995),Drama
23,193,1233,5,"Boat, The (Das Boot) (1981)",Action|Drama|War
24,193,1235,5,Harold and Maude (1971),Comedy

1. 193번은 보고 5번은 안본 영화
2. recommendation_data에서 위의 1번 결과에 해당하는 목록을 가져옴   
3. Rating이 5점이고 193이 본 영화 목록을 가져와서 영화제목과 장르를 연결

In [ ]:
#user_id(193)
#other_id(5)

def unseen_movie(user_id, other_id):
  unseen = set(movie_seen(user_id).index)- set(movie_seen(other_id).index)
  unseen_movie = recommendation_data[recommendation_data.MovieID.isin(unseen)]
  return unseen_movie[(unseen_movie.Rating==5) & (unseen_movie.UserID==user_id)].merge(movies)

In [ ]:
# 193번은 보고 5번은 보지 않은 영화중에 평점 5인 영화를 유저 5번에 추천
unseen_movie(193, 5)

,UserID,MovieID,Rating,Title,Genres
0,193,649,5,Cold Fever (Á köldum klaka) (1994),Comedy|Drama
1,193,1188,5,Strictly Ballroom (1992),Comedy|Romance
2,193,2208,5,"Lady Vanishes, The (1938)",Comedy|Mystery|Romance|Thriller
3,193,1265,5,Groundhog Day (1993),Comedy|Romance
4,193,1197,5,"Princess Bride, The (1987)",Action|Adventure|Comedy|Romance
5,193,2150,5,"Gods Must Be Crazy, The (1980)",Comedy
6,193,1358,5,Sling Blade (1996),Drama|Thriller
7,193,912,5,Casablanca (1942),Drama|Romance|War
8,193,922,5,Sunset Blvd. (a.k.a. Sunset Boulevard) (1950),Film-Noir
9,193,926,5,All About Eve (1950),Drama
10,193,928,5,Rebecca (1940),Romance|Thriller
11,193,1639,5,Chasing Amy (1997),Drama|Romance
12,193,899,5,Singin' in the Rain (1952),Musical|Romance
13,193,1648,5,"House of Yes, The (1997)",Comedy|Drama|Thriller
14,193,2520,5,Airport (1970),Drama
15,193,1748,5,Dark City (1998),Film-Noir|Sci-Fi|Thriller
16,193,3469,5,Inherit the Wind (1960),Drama
17,193,21,5,Get Shorty (1995),Action|Comedy|Drama
18,193,1104,5,"Streetcar Named Desire, A (1951)",Drama
19,193,3671,5,Blazing Saddles (1974),Comedy|Western
20,193,1136,5,Monty Python and the Holy Grail (1974),Comedy
21,193,1148,5,"Wrong Trousers, The (1993)",Animation|Comedy
22,193,82,5,Antonia's Line (Antonia) (1995),Drama
23,193,1233,5,"Boat, The (Das Boot) (1981)",Action|Drama|War
24,193,1235,5,Harold and Maude (1971),Comedy

7번과 유사한 2명 뽑아서 둘 중 한명이라고 평점이 5점인 영화 추천

In [ ]:
# 유저7과 유사한 2명 가져옴  (288,251)
def nearest_user(user_id, n):
   return  small_test_corr.loc[user_id].sort_values(ascending=False)[1:n+1]


def movie_seen(user):
   return recommendation_pivot.loc[user][recommendation_pivot.loc[user]>0]

In [ ]:
movie_seen(288)

MovieID
21      3.0
110     5.0
260     5.0
349     4.0
377     5.0
380     5.0
474     4.0
480     4.0
494     4.0
733     4.0
912     4.0
1036    5.0
1101    5.0
1127    4.0
1196    5.0
1197    5.0
1198    5.0
1200    5.0
1210    5.0
1222    4.0
1240    5.0
1242    5.0
1275    4.0
1291    5.0
1356    4.0
1374    5.0
1376    4.0
1429    4.0
1573    5.0
1580    5.0
1610    5.0
1727    4.0
1912    4.0
1918    4.0
2000    5.0
2001    5.0
2058    5.0
2135    5.0
2167    5.0
2273    5.0
2278    5.0
2353    5.0
2406    5.0
2571    5.0
2916    5.0
2947    5.0
2993    3.0
3350    5.0
3398    3.0
3418    5.0
3527    5.0
3635    5.0
3702    4.0
3793    5.0
3827    5.0
3911    4.0
Name: 288, dtype: float64

In [ ]:
nearest_user(7, 2)

UserID
288    0.676216
251    0.674230
Name: 7, dtype: float64

In [ ]:
nearest_user(7, 2).shape

(2,)

In [ ]:
# 각각의 유저는 user0, user1로 해준다.
user0 = nearest_user(7, 2).index[0]  #288
user1 = nearest_user(7,2).index[1]   #251
print(user0, user1)

288 251

In [ ]:
userlist =  nearest_user(7, 2).index
print(userlist[0])
print(userlist[1])

288
251

In [ ]:
movie_seen(user0)

MovieID
21      3.0
110     5.0
260     5.0
349     4.0
377     5.0
380     5.0
474     4.0
480     4.0
494     4.0
733     4.0
912     4.0
1036    5.0
1101    5.0
1127    4.0
1196    5.0
1197    5.0
1198    5.0
1200    5.0
1210    5.0
1222    4.0
1240    5.0
1242    5.0
1275    4.0
1291    5.0
1356    4.0
1374    5.0
1376    4.0
1429    4.0
1573    5.0
1580    5.0
1610    5.0
1727    4.0
1912    4.0
1918    4.0
2000    5.0
2001    5.0
2058    5.0
2135    5.0
2167    5.0
2273    5.0
2278    5.0
2353    5.0
2406    5.0
2571    5.0
2916    5.0
2947    5.0
2993    3.0
3350    5.0
3398    3.0
3418    5.0
3527    5.0
3635    5.0
3702    4.0
3793    5.0
3827    5.0
3911    4.0
Name: 288, dtype: float64

In [ ]:
# user0(288)본 MovieID을 가져온다.
movie_seen(user0).index

Index([  21,  110,  260,  349,  377,  380,  474,  480,  494,  733,  912, 1036,
       1101, 1127, 1196, 1197, 1198, 1200, 1210, 1222, 1240, 1242, 1275, 1291,
       1356, 1374, 1376, 1429, 1573, 1580, 1610, 1727, 1912, 1918, 2000, 2001,
       2058, 2135, 2167, 2273, 2278, 2353, 2406, 2571, 2916, 2947, 2993, 3350,
       3398, 3418, 3527, 3635, 3702, 3793, 3827, 3911],
      dtype='int64', name='MovieID')

In [ ]:
# user1(251)본 MovieID을 가져온다.
movie_seen(user1).index

Index([   6,   11,   21,   32,  110,  210,  266,  316,  349,  368,  377,  380,
        383,  435,  457,  474,  480,  553,  589,  590,  594,  780, 1047, 1079,
       1081, 1220, 1233, 1259, 1266, 1270, 1307, 1320, 1370, 1372, 1379, 1408,
       1580, 1610, 1663, 1721, 1748, 1958, 1968, 2000, 2012, 2028, 2046, 2058,
       2065, 2094, 2174, 2474, 2716, 2795, 2804, 2915, 2916, 2918, 3072, 3256,
       3361, 3418, 3448, 3697, 3916, 3927, 3928, 3930, 3936, 3937, 3946, 3948,
       3952],
      dtype='int64', name='MovieID')

In [ ]:
# user0(288)과 user1(251)이 본 영화중 5점인 영화 MovieID을 가져온다.

def recommend_movie(user_id, n):
  user_list = nearest_user(user_id, n).index

  #user0(288)과 user1(251)
  user_mv_list = recommendation_data[(recommendation_data.UserID.isin(user_list)) & (recommendation_data.Rating==5)]
  print(user_mv_list.columns)

  # UserID 7번이 본 영화목록
  user7_mv_list = movie_seen(user_id)

  # UserID 288번이나  251번이  본 영화이지만 7번은 보지 않는 영화
  unseen_list = set(user_mv_list['MovieID']) - set(user7_mv_list.index)

  return movies[movies['MovieID'].isin(unseen_list)].reset_index(drop=True)

In [ ]:
test = recommend_movie(7,2)
print(test)

Index(['UserID', 'MovieID', 'Rating'], dtype='object')
    MovieID                                              Title  \
0        21                                  Get Shorty (1995)
1       260          Star Wars: Episode IV - A New Hope (1977)
2      1036                                    Die Hard (1988)
3      1079                        Fish Called Wanda, A (1988)
4      1101                                     Top Gun (1986)
5      1197                         Princess Bride, The (1987)
6      1198                     Raiders of the Lost Ark (1981)
7      1200                                      Aliens (1986)
8      1210  Star Wars: Episode VI - Return of the Jedi (1983)
9      1240                             Terminator, The (1984)
10     1242                                       Glory (1989)
11     1291          Indiana Jones and the Last Crusade (1989)
12     1374                Star Trek: The Wrath of Khan (1982)
13     1408                   Last of the Mohicans, The (1992)
14     1721                                     Titanic (1997)
15     2000                               Lethal Weapon (1987)
16     2001                             Lethal Weapon 2 (1989)
17     2058                             Negotiator, The (1998)
18     2135                             Doctor Dolittle (1967)
19     2167                                       Blade (1998)
20     2273                                   Rush Hour (1998)
21     2278                                       Ronin (1998)
22     2406                         Romancing the Stone (1984)
23     2947                                  Goldfinger (1964)
24     3350                        Raisin in the Sun, A (1961)
25     3527                                    Predator (1987)
26     3635                       Spy Who Loved Me, The (1977)
27     3827                               Space Cowboys (2000)

                                 Genres
0                   Action|Comedy|Drama
1       Action|Adventure|Fantasy|Sci-Fi
2                       Action|Thriller
3                                Comedy
4                        Action|Romance
5       Action|Adventure|Comedy|Romance
6                      Action|Adventure
7            Action|Sci-Fi|Thriller|War
8   Action|Adventure|Romance|Sci-Fi|War
9                Action|Sci-Fi|Thriller
10                     Action|Drama|War
11                     Action|Adventure
12              Action|Adventure|Sci-Fi
13                   Action|Romance|War
14                        Drama|Romance
15            Action|Comedy|Crime|Drama
16            Action|Comedy|Crime|Drama
17                      Action|Thriller
18                    Adventure|Musical
19              Action|Adventure|Horror
20                      Action|Thriller
21                Action|Crime|Thriller
22      Action|Adventure|Comedy|Romance
23                               Action
24                                Drama
25               Action|Sci-Fi|Thriller
26                               Action
27                        Action|Sci-Fi

In [ ]:
user7_mv_list = movie_seen(7).index
print(user7_mv_list)

Index([   6,  110,  349,  377,  380,  442,  457,  474,  480,  589,  648,  733,
        861, 1196, 1221, 1270, 1573, 1580, 1610, 1722, 1997, 2028, 2353, 2571,
       2916, 3107, 3256, 3418, 3578, 3753, 3793],
      dtype='int64', name='MovieID')

In [ ]:
len((set(test['MovieID']) - set(movie_seen(7).index)))

28

In [ ]:
len(test['MovieID'])

28

In [ ]:
%%writefile movie_systme.py

import numpy as np
import pandas as pd
import matplotlib as mp
import matplotlib.pyplot as plt
import seaborn as sns

#파일 로딩
def data_load():
  movies = pd.read_csv('./raw/m1/movies.dat', delimiter='::', header=None, engine='python', encoding='ISO-8859-1',
                    names=['MovieID', 'Title', 'Genres'] )
  users = pd.read_csv('./raw/m1/users.dat', sep='::', engine='python',header=None,
                    names=['UserID','Gender','Age','Occupation','Zip-code'])
  ratings = pd.read_csv('./raw/m1/ratings.dat', sep='::', engine='python', header=None,
                    names=['UserID','MovieID','Rating','Timestamp'])
  return movies, users, ratings

# merge
def data_merge(movies, users, ratings):
  data = ratings.merge(users).merge(movies)
  recommendation_data = data[['UserID', 'MovieID', 'Rating']]
  return recommendation_data

#  pivot, corr
def data_pivot_corr(recommendation_data):
  recommendation_pivot = recommendation_data.pivot(index ='UserID', columns='MovieID', values='Rating')
  recommendation_pivot.fillna(0, inplace=True)
  return recommendation_pivot

def nearest_user(small_test_corr, user_id, n):
  return small_test_corr.loc[user_id].sort_values(ascending =False)[1: n+1]

def movie_seen(user_id):
   return recommendation_pivot.loc[user_id][recommendation_pivot.loc[user_id]>0]

def recommend_movie(recommendation_pivot, movies, user_id, n):
  small_test_corr = recommendation_pivot.T.iloc[:500,:500].corr()
  user_list = nearest_user(small_test_corr, user_id, n).index
  user_mv_list = recommendation_data[(recommendation_data.UserID.isin(user_list)) & (recommendation_data.Rating==5)]
  user7_mv_list = movie_seen(user_id)
  unseen_list = set(user_mv_list['MovieID']) - set(user7_mv_list.index)
  return movies[movies['MovieID'].isin(unseen_list)].reset_index(drop=True)

if __name__  == '__main__':
  movies, users, ratings = data_load()
  recommendation_data = data_merge(movies, users, ratings)
  recommendation_pivot = data_pivot_corr(recommendation_data)
  userid =  int(input('UserId 입력:'))
  movie_receive = recommend_movie(recommendation_pivot, movies,  userid, 2)
  print(len(movie_receive))
  print(movie_receive)

Overwriting movie_systme.py

In [ ]:
!pwd

/content/drive/MyDrive/의료_Medical_AI_분석개발자과정/AI

In [ ]:
!python  movie_systme.py

153
UserId 입력:13
    MovieID  ...                           Genres
0        22  ...             Crime|Drama|Thriller
1       110  ...                 Action|Drama|War
2       480  ...          Action|Adventure|Sci-Fi
3       589  ...           Action|Sci-Fi|Thriller
4       594  ...     Animation|Children's|Musical
5      1569  ...                   Comedy|Romance
6      1580  ...   Action|Adventure|Comedy|Sci-Fi
7      1680  ...                    Drama|Romance
8      1835  ...                          Romance
9      2628  ...  Action|Adventure|Fantasy|Sci-Fi
10     2724  ...                   Comedy|Romance
11     2791  ...                           Comedy
12     3160  ...                            Drama

[13 rows x 3 columns]

streamlit 생성

In [ ]:
# !uv add streamlit

Collecting streamlit
  Downloading streamlit-1.47.1-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.5.2)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (8.2.1)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging<26,>=20 in /usr/local/lib/python3.11/dist-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<12,>=7.1.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.29.5)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.32.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (8.5.0)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.11/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (4.14.1)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Downloading watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.3/44.3 kB 2.0 MB/s eta 0:00:00
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.11/dist-packages (from streamlit) (3.1.45)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.11/dist-packages (from streamlit) (6.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (4.25.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (1.48.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (2025.7.14)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.26.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.47.1-py3-none-any.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 48.3 MB/s eta 0:00:00
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 97.1 MB/s eta 0:00:00
Downloading watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl (79 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 6.4 MB/s eta 0:00:00
Installing collected packages: watchdog, pydeck, streamlit
Successfully installed pydeck-0.9.1 streamlit-1.47.1 watchdog-6.0.0

In [ ]:
#%%writefile streamlit_app.py
import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import os


# 데이터 로딩
@st.cache_data
def data_load():
    movies = pd.read_csv('./raw/m1/movies.dat', delimiter='::', header=None, engine='python', encoding='ISO-8859-1',
                         names=['MovieID', 'Title', 'Genres'])
    users = pd.read_csv('./raw/m1/users.dat', sep='::', engine='python', header=None,
                        names=['UserID', 'Gender', 'Age', 'Occupation', 'Zip-code'])
    ratings = pd.read_csv('./raw/m1/ratings.dat', sep='::', engine='python', header=None,
                          names=['UserID', 'MovieID', 'Rating', 'Timestamp'])
    return movies, users, ratings

# merge
@st.cache_data
def data_merge(movies, users, ratings):
    data = ratings.merge(users).merge(movies)
    recommendation_data = data[['UserID', 'MovieID', 'Rating']]
    return data, recommendation_data

# pivot
@st.cache_data
def data_pivot_corr(recommendation_data):
    pivot = recommendation_data.pivot(index='UserID', columns='MovieID', values='Rating')
    pivot.fillna(0, inplace=True)
    return pivot

# 유사 사용자
def nearest_user(corr_matrix, user_id, n):
    return corr_matrix.loc[user_id].sort_values(ascending=False)[1:n+1]

# 본 영화 목록
def movie_seen(recommendation_pivot, user_id, movies):
    seen = recommendation_pivot.loc[user_id][recommendation_pivot.loc[user_id] > 0]
    return movies[movies['MovieID'].isin(seen.index)].assign(MyRating=seen.values)

# 추천
def recommend_movie(pivot, data, movies, user_id, n=2):
    corr = pivot.T.iloc[:500, :500].corr()
    similar_users = nearest_user(corr, user_id, n).index
    sim_user_corr = nearest_user(corr, user_id, n)
    similar_data = data[(data.UserID.isin(similar_users)) & (data.Rating == 5)]
    seen = pivot.loc[user_id][pivot.loc[user_id] > 0]
    unseen = set(similar_data['MovieID']) - set(seen.index)
    return movies[movies['MovieID'].isin(unseen)].reset_index(drop=True), sim_user_corr



# main
def main():

    st.title("사용자 기반 영화 추천 시스템")
    st.markdown("**유사 사용자 기반 협업 필터링**으로 추천합니다.")


    with st.spinner("데이터 로딩 중..."):
        movies, users, ratings = data_load()
        full_data, recommendation_data = data_merge(movies, users, ratings)
        pivot = data_pivot_corr(recommendation_data)

    user_id = st.selectbox("사용자 선택", pivot.index.tolist())
    top_n = st.slider("추천받을 영화 수", 1, 10, 3)

    if st.button("영화 추천받기"):
        with st.spinner("추천 처리 중..."):
            recommended_movies, sim_user_corr = recommend_movie(pivot, recommendation_data, movies, user_id, top_n)
            seen_movies = movie_seen(pivot, user_id, movies)

        st.subheader("내가 본 영화 목록")
        st.dataframe(seen_movies[['Title', 'Genres', 'MyRating']].sort_values('MyRating', ascending=False))

        st.subheader("유사 사용자 Top-N")
        st.table(pd.DataFrame({
            "UserID": sim_user_corr.index,
            "상관계수": sim_user_corr.values
        }))

        st.subheader("유사 사용자 상관계수 시각화")
        fig, ax = plt.subplots(figsize=(6, 4))
        sns.barplot(x=sim_user_corr.values, y=sim_user_corr.index, ax=ax)
        ax.set_xlabel("상관계수")
        ax.set_ylabel("UserID")
        ax.set_title("Top-N 유사 사용자 상관계수")
        st.pyplot(fig)

        st.subheader("추천 영화 목록")
        st.dataframe(recommended_movies[['Title', 'Genres']])

if __name__ == '__main__':
    main()

FileNotFoundError: [Errno 2] No such file or directory: '/content/Nanum_Gothic/NanumGothic-Bold.ttf'